vich_uploader:
    db_driver: orm

    mappings:
        pan_image:
            uri_prefix: /uploads/pans
            upload_destination: '%kernel.project_dir%/public/img/uploads/pans'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
